color molokai

if has("gui_running")
    set transparency=10

    " Remove the toolbar.
    set guioptions-=T

    " Remove the left-hand scrollbar.
    set guioptions-=l
    set guioptions-=L

    " Remove the right-hand scrollbar.
    set guioptions-=r

    " Static syntax checker.
    autocmd BufWritePost *.py call CheckPy()

    function CheckPy()
        if getline(1) == "# -*- coding: utf-8 -*-"
            call Flake8()
        endif
    endfunction
endif

" Tab settings.
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Determine listing exclusions.
set wildignore+=.DS_Store,*.egg,*.egg-info,*.py[co]

" NERDTree setting.
let NERDTreeIgnore = ["\.DS_Store","\.egg","\.egg-info","\.py[co]"]
let NERDTreeShowHidden = 1

" Remove trailing whitespace.
autocmd BufWritePre * :%s/\s\+$//e

" File types.
autocmd BufNewFile,BufRead *.ccss setlocal ft=clevercss
autocmd BufNewFile,BufRead */*templates*.html setlocal ft=htmljinja.html textwidth=0
autocmd Filetype ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2
