color molokai

if has("gui_running")
    set transparency=10

    " Remove the toolbar.
    set guioptions-=T

    " Remove the left-hand scrollbar.
    set guioptions-=l
    set guioptions-=L

    " Remove the right-hand scrollbar.
    set guioptions-=r
endif

" Tab settings.
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Determine listing exclusions.
set wildignore+=.DS_Store,*.egg,*.egg-info,*.py[co],log,tmp

" NERDTree setting.
let NERDTreeIgnore = ["\.DS_Store","\.egg","\.egg-info","\.py[co]"]
let NERDTreeShowHidden = 1
let NERDTreeShowLineNumbers = 1

" Syntastic settings.
let g:syntastic_auto_loc_list = 1
let g:syntastic_html_tidy_exec = "tidy5"
let g:syntastic_javascript_checkers = ["eslint"]
let g:syntastic_python_checkers = ["flake8"]
let g:syntastic_python_flake8_quiet_messages = {"regex": "E128"}
let g:syntastic_ruby_checkers = ["rubocop"]
let g:syntastic_scss_checkers = ["scss_lint"]

" Remove trailing whitespace.
autocmd BufWritePre * :%s/\s\+$//e

" File types.
autocmd BufNewFile,BufRead Makefile setlocal noexpandtab
autocmd BufNewFile,BufRead *.ccss setlocal ft=clevercss
autocmd BufNewFile,BufRead *.pp setlocal ft=ruby
autocmd BufNewFile,BufRead *.tag setlocal ft=html
autocmd BufNewFile,BufRead */*templates*.html setlocal ft=htmljinja.html textwidth=0
autocmd Filetype ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype stylus setlocal shiftwidth=4

" Key mappings.
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

" Local vimrc
if filereadable('.vimrc.local')
    source .vimrc.local
endif
